interface Achievement {
  id: string
  title: string
  description: string
  difficulty: string
  condition: number
  modifier: number
}
type AchievementConfig = Record<string, Record<string, Achievement[]>>

// Feature{} > Achievement[] per category > Achievement{}
export const ACHIEVEMENT_CONFIG: AchievementConfig = {
  zone: {
    count: [
      {
        id: "zone-count.1",
        title: "TODO",
        description: "Complete 50 zones",
        difficulty: "beginner",
        condition: 50,
        modifier: 0.05,
      },
      {
        id: "zone-count.2",
        title: "TODO",
        description: "Complete 250 zones",
        difficulty: "beginner",
        condition: 250,
        modifier: 0.05,
      },
      {
        id: "zone-count.3",
        title: "TODO",
        description: "Complete 500 zones",
        difficulty: "novice",
        condition: 500,
        modifier: 0.1,
      },
      {
        id: "zone-count.4",
        title: "TODO",
        description: "Complete 1000 zones",
        difficulty: "novice",
        condition: 1000,
        modifier: 0.1,
      },
      {
        id: "zone-count.5",
        title: "TODO",
        description: "Complete 2500 zones",
        difficulty: "intermediate",
        condition: 2500,
        modifier: 0.2,
      },
    ],
    progression: [
      {
        id: "zone-progression.1",
        title: "First Steps",
        description: "Complete zone 10",
        difficulty: "beginner",
        condition: 10,
        modifier: 0.05,
      },
      {
        id: "zone-progression.2",
        title: "The Regions",
        description: "Complete zone 20",
        difficulty: "novice",
        condition: 20,
        modifier: 0.1,
      },
      {
        id: "zone-progression.3",
        title: "The Rhythms",
        description: "Complete zone 30",
        difficulty: "intermediate",
        condition: 30,
        modifier: 0.2,
      },
    ],
    farm: [
      {
        id: "zone-farm.1",
        title: "Farmhand",
        description: "Complete 10 farm zones",
        difficulty: "beginner",
        condition: 10,
        modifier: 0.05,
      },
      {
        id: "zone-farm.2",
        title: "Farmer",
        description: "Complete 50 farm zones",
        difficulty: "beginner",
        condition: 50,
        modifier: 0.05,
      },
      {
        id: "zone-farm.3",
        title: "Agriculturalist",
        description: "Complete 100 farm zones",
        difficulty: "beginner",
        condition: 100,
        modifier: 0.05,
      },
      {
        id: "zone-farm.4",
        title: "Modern Farmer I: Youtube Thumbnail Artist",
        description: "Complete 250 farm zones",
        difficulty: "novice",
        condition: 250,
        modifier: 0.1,
      },
      {
        id: "zone-farm.5",
        title: "Modern Farmer II: Relationship Drama Post by ChatGPT",
        description: "Complete 1000 farm zones",
        difficulty: "novice",
        condition: 1000,
        modifier: 0.1,
      },
      {
        id: "zone-farm.6",
        title: "Modern Farmer III: Sleeping Livestream",
        description: "Complete 5000 farm zones",
        difficulty: "novice",
        condition: 5000,
        modifier: 0.1,
      },
      {
        id: "zone-farm.7",
        title: "Modern Farmer IV: Automated Harvest Hero",
        description: "Complete 10000 farm zones",
        difficulty: "intermediate",
        condition: 10000,
        modifier: 0.2,
      },
      {
        id: "zone-farm.8",
        title: "Modern Farmer V: Eco-Friendly Innovator",
        description: "Complete 15000 farm zones",
        difficulty: "intermediate",
        condition: 15000,
        modifier: 0.2,
      },
      {
        id: "zone-farm.9",
        title: "Modern Farmer VI: ChatGPT Wrote The Last 2 Farming Achievements",
        description: "Complete 20000 farm zones",
        difficulty: "intermediate",
        condition: 20000,
        modifier: 0.2,
      },
    ],
  },
  click: {
    count: [
      {
        id: "click-count.1",
        title: "Clicker",
        description: "Click monsters 100 times",
        difficulty: "beginner",
        condition: 100,
        modifier: 0.05,
      },
      {
        id: "click-count.2",
        title: "Mouse User",
        description: "Click monsters 500 times",
        difficulty: "beginner",
        condition: 500,
        modifier: 0.05,
      },
      {
        id: "click-count.3",
        title: "Certified Mouse User",
        description: "Click monsters 1000 times",
        difficulty: "beginner",
        condition: 1000,
        modifier: 0.05,
      },
      {
        id: "click-count.3",
        title: "Certificate in Applied Mouse Usership: Full Range-Of-Motion Clicker",
        description: "Click monsters 2500 times",
        difficulty: "novice",
        condition: 2500,
        modifier: 0.1,
      },
      {
        id: "click-count.4",
        title: "Bachelor of Mouse Operations",
        description: "Click monsters 10000 times",
        difficulty: "novice",
        condition: 10000,
        modifier: 0.1,
      },
      {
        id: "click-count.5",
        title: "Doctor of Pointer Arithmetic",
        description: "Click monsters 25000 times",
        difficulty: "intermediate",
        condition: 25000,
        modifier: 0.2,
      },
    ],
    damage: [
      {
        id: "click-damage.1",
        title: "Slime Splattered Mouse",
        description: "Deal 5000 click damage",
        difficulty: "beginner",
        condition: 5000,
        modifier: 0.05,
      },
      {
        id: "click-damage.2",
        title: "Mouse-based Harm Enthusiast",
        description: "deal 25000 click damage",
        difficulty: "beginner",
        condition: 25000,
        modifier: 0.05,
      },
      {
        id: "click-damage.3",
        title: "Scroll Wheel Slime Keelhauling",
        description: "deal 100000 click damage",
        difficulty: "novice",
        condition: 100000,
        modifier: 0.1,
      },
      {
        id: "click-damage.4",
        title: "Drawn Quartered on the Palm Rest",
        description: "deal 500000 click damage",
        difficulty: "novice",
        condition: 500000,
        modifier: 0.1,
      },
      {
        id: "click-damage.5",
        title: "DPI Disembowelment",
        description: "deal 10000000 click damage",
        difficulty: "intermediate",
        condition: 10000000,
        modifier: 0.2,
      },
    ],
  },
  dot: {
    value: [
      {
        id: "dot-value.1",
        title: "TODO",
        description: "Deal 100 Damage Per Second",
        difficulty: "beginner",
        condition: 100,
        modifier: 0.05,
      },
      {
        id: "dot-value.2",
        title: "TODO",
        description: "Deal 1000 Damage Per Second",
        difficulty: "beginner",
        condition: 1000,
        modifier: 0.05,
      },
      {
        id: "dot-value.3",
        title: "TODO",
        description: "Deal 10000 Damage Per Second",
        difficulty: "novice",
        condition: 10000,
        modifier: 0.1,
      },
      {
        id: "dot-value.4",
        title: "TODO",
        description: "Deal 25000 Damage Per Second",
        difficulty: "novice",
        condition: 25000,
        modifier: 0.1,
      },
      {
        id: "dot-value.5",
        title: "TODO",
        description: "Deal 100000 Damage Per Second",
        difficulty: "intermediate",
        condition: 100000,
        modifier: 0.2,
      },
    ],
    damage: [
      {
        id: "dot-damage.1",
        title: "TODO",
        description: "Deal 10000 Damage Passively",
        difficulty: "beginner",
        condition: 1000,
        modifier: 0.05,
      },
      {
        id: "dot-damage.2",
        title: "TODO",
        description: "Deal 100000 Damage Passively",
        difficulty: "beginner",
        condition: 100000,
        modifier: 0.05,
      },
      {
        id: "dot-damage.3",
        title: "TODO",
        description: "Deal 1000000 Damage Passively",
        difficulty: "novice",
        condition: 1000000,
        modifier: 0.1,
      },
      {
        id: "dot-damage.4",
        title: "TODO",
        description: "Deal 10000000 Damage Passively",
        difficulty: "novice",
        condition: 10000000,
        modifier: 0.1,
      },
      {
        id: "dot-damage.5",
        title: "TODO",
        description: "Deal 100000000 Damage Passively",
        difficulty: "intermediate",
        condition: 100000000,
        modifier: 0.2,
      },
    ],
  },
  prestige: {
    count: [
      {
        id: "prestige-count.1",
        title: "Stratigraphy of Rock Bottom",
        description: "Prestige 1 time",
        difficulty: "beginner",
        condition: 1,
        modifier: 0.05,
      },
      {
        id: "prestige-count.2",
        title: "TODO",
        description: "Prestige 3 times",
        difficulty: "beginner",
        condition: 3,
        modifier: 0.05,
      },
      {
        id: "prestige-count.3",
        title: "TODO",
        description: "Prestige 10 times",
        difficulty: "novice",
        condition: 10,
        modifier: 0.1,
      },
      {
        id: "prestige-count.4",
        title: "TODO",
        description: "Prestige 15 times",
        difficulty: "novice",
        condition: 15,
        modifier: 0.1,
      },
      {
        id: "prestige-count.5",
        title: "TODO",
        description: "Prestige 20 times",
        difficulty: "intermediate",
        condition: 20,
        modifier: 0.2,
      },
    ],
    plasmaSpent: [
      {
        id: "prestige-plasmaspent.1",
        title: "Reveries in Autocytoplasm",
        description: "Spend 100 Plasma",
        difficulty: "beginner",
        condition: 100,
        modifier: 0.05,
      },
      {
        id: "prestige-plasmaspent.2",
        title: "Exquisite Paroxsyms of Progress",
        description: "Spend 1000 Plasma",
        difficulty: "beginner",
        condition: 1000,
        modifier: 0.05,
      },
      {
        id: "prestige-plasmaspent.3",
        title: "TODO",
        description: "Spend 10000 Plasma",
        difficulty: "novice",
        condition: 10000,
        modifier: 0.1,
      },
      {
        id: "prestige-plasmaspent.4",
        title: "TODO",
        description: "Spend 100000 Plasma",
        difficulty: "novice",
        condition: 100000,
        modifier: 0.1,
      },
      {
        id: "prestige-plasmaspent.5",
        title: "TODO",
        description: "Spend 1000000 Plasma",
        difficulty: "intermediate",
        condition: 1000000,
        modifier: 0.2,
      },
    ],
  },
} as const
